name: functionapp deployment

on:
  workflow_dispatch: #lets you run the workflow manually
  # push:
  #   branches:
  #   - main

env:
  AZURE_FUNCTIONAPP_NAME: deployment-fnctionapp
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "./Test_Functions"
  DOTNET_VERSION: '6.0.x' 

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: "Setup .NET"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION}}
          
      - name: Restore
        run: dotnet restore ./Test_Functions
        
      # - name: Build
      #   run: dotnet build ./Test_Functions --configuration Release --no-restore

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --no-restore --output ./output
          popd

      # - name: Publish
      #   run: dotnet publish ./Test_Functions --configuration Release --no-build

      - name: "Deploy package to function app"
        uses: azure/functions-action@v1
        with: 
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
     



        

     
