name: webapp deployment

on:
  workflow_dispatch:
  push:
    branches: ["master"] 

# permissions: read

env:
  AZURE_WEBAPP_NAME: "webapp-deploy-actions"
  AZURE_WEBAPP_PACKAGE_PATH: ./Test_WebApp
  # AZURE-WEBAPP-USER-PROFILE:
  DOTNET-VERSION: "6.0.x"

jobs:
  build:
    runs-on: windows-latest
      
    steps:
    - name: Checkout action
      uses: actions/checkout@v3
    
    # - name: Setup .NETCORE  
    #   uses: actions/setup-dotnet@v3
    #   with: 
    #     dotnet-version: ${{ env.DOTNET-VERSION }}

    - name: NuGet to restore dependencies as well as project-specific tools that are specified in the project file
      run: nuget restore
      
    - name: Restore
      run: dotnet restore ./Test_Functions
      
    # - name: Build
    #   run: dotnet build ./Test_Functions --configuration Release --no-restore

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
        pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --no-restore --output ./output
        popd
      
    - name: Run MSBuild
      run: msbuild ./Test_WebApp
       
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
  
     
    
  
