name: webapp deployment

on:
  workflow_dispatch:
  push:
    branches: ["master"] 

# permissions: read

env:
  AZURE_WEBAPP_NAME: "webapp-deploy-actions"
  AZURE_WEBAPP_PACKAGE_PATH: ./Test_WebApp
  # AZURE-WEBAPP-USER-PROFILE:
  DOTNET-VERSION: "6.0.x"

jobs:
  build:
    runs-on: windows-latest
      
    steps:
    - name: Checkout action
      uses: actions/checkout@v3

    - name: setup npm
      uses: actions/setup-node@v3

    - name: npm build and run
      uses: |
        npm build
        npm run

    - name: Restore
      run: dotnet restore ./Test_Functions

    - name: 'Resolve Project Dependencies Using Dotnet'
      shell: bash
      run: |
        pushd '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --no-restore --output ./output
        popd
    
  
  # deploy:
  #   runs-on: windows-latest

  #   steps:
  #   - name: 'Run Azure webapp deploy action using publish profile credentials'
  #     uses: azure/webapps-deploy@v2
  #     with: 
  #       app-name: ${{ env.AZURE_WEBAPP_NAME }} # Replace with your app name
  #       publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
  #       package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
  
     
    
  
